name: Build and Push Docker Image (Master Branch)

on:
  workflow_run:
    workflows: ["Python SSL Checker Tests"]
    types: [completed]

permissions:
  contents: read

jobs:
  docker-build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "sentinelkasai/ssl-checker:master"
      
      - name: Discord Notification (Success)
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "embeds": [{
                "title": "✅ Docker Image Pushed",
                "description": "The image **sentinelkasai/ssl-checker:master** has been successfully pushed to Docker Hub.",
                "color": 3066993,
                "timestamp": "'"$(date --utc +%Y-%m-%dT%H:%M:%SZ)"'",
                "footer": { "text": "GitHub Actions • Build Success" }
              }]
            }' \
            $DISCORD_WEBHOOK

      - name: Discord Notification (Failure)
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "embeds": [{
                "title": "❌ Docker Build/Push Failed",
                "description": "Docker build or push failed for **sentinelkasai/ssl-checker:master**.",
                "color": 15158332,
                "timestamp": "'"$(date --utc +%Y-%m-%dT%H:%M:%SZ)"'",
                "footer": { "text": "GitHub Actions • Build Failure" }
              }]
            }' \
            $DISCORD_WEBHOOK
